config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/info'
  mount Commontator::Engine => '/commontator'

  root to: redirect('/ideas')

  resources :ideas do
    member do
      put 'like', to: 'ideas#upvote'
      put 'dislike', to: 'ideas#downvote'
    end
  end

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
  acts_as_commontable
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ideas
  acts_as_commontator
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    commontator_thread_show(@idea)
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
    @idea = current_user.ideas.find_by_id(params[:id])
    if @idea.nil?
      redirect_to ideas_path, flash: {alert: 'No existe la idea que desea modificar'}
    end
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    @idea = current_user.ideas.find(params[:id])
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @idea = Idea.find(params[:id])
    @idea.upvote_by current_user
    redirect_to ideas_path
  end

  def downvote
    @idea = Idea.find(params[:id])
    @idea.downvote_by current_user
    redirect_to ideas_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ideas/_form.html.erb
<div class="col-md-5">
  <%= form_for(@idea, html: {role: 'form'}) do |f| %>
    <% if @idea.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

        <ul>
        <% @idea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Nombre' %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', placeholder: 'Descripción' %>
    </div>
    <div class="form-group">
      <%= f.label :picture %>
      <%= f.file_field :picture %>
    </div>

    <%= f.submit class: 'btn btn-default' %>
    <%= link_to 'Back', ideas_path, class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/ideas/edit.html.erb
<h1>Edit - <%= @idea.name %></h1>

<%= render 'form' %>

app/views/ideas/index.html.erb
<h1>Listing Ideas</h1>

<% @ideas.in_groups_of(6) do |group| %>
  <div class="row">
    <% group.compact.each do |idea| %>
      <div class="col-md-2">
        <%= link_to idea do %>
          <div class="grid-image-container">
            <%= image_tag idea.picture_url, class: 'img-thumbnail grid-image' if idea.picture.present?%>
          </div>
        <% end %>
        <h4>
          <%= link_to idea.name, idea %>
          <small class="pull-right votes-container">
            <%= link_to like_idea_path(idea), method: :put do %>
              <span class="<%= current_user.voted_up_on?(idea) ? "selected blue" : "" %> votes">
                <%= idea.get_upvotes.size %>
                <span class="glyphicon glyphicon-arrow-up"></span>
              </span>
            <% end %>
            <%= link_to dislike_idea_path(idea), method: :put do %>
              <span class="<%= current_user.voted_down_on?(idea) ? "red" : "" %> votes">
                <%= idea.get_downvotes.size %>
                <span class="glyphicon glyphicon-arrow-down"></span>
              </span>
            <% end %>
          </small>
        </h4>
        <p>
          <%= idea.description %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-9">
    <%= image_tag(@idea.picture_url, width: '100%') if @idea.picture.present? %>
  </div>

  <div class="col-md-3">
    <p><b>Name: </b><%= @idea.name %></p>
    <p><b>Description: </b><%= @idea.description %></p>
    <p>
      <% if current_user.ideas.include? @idea %>
        <%= link_to 'Edit', edit_idea_path(@idea) %> |
        <%= link_to 'Destroy', @idea, data: { confirm: 'Are you sure?' }, method: :delete %> |
      <% end %>
      <%= link_to 'Back', ideas_path %>
    </p>
  </div>
</div>

<%= commontator_thread(@idea) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">The Idea app</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if current_page?(ideas_path) %>">
            <%= link_to 'Ideas', ideas_path %>
          </li>
          <li class="<%= 'active' if current_page?(pages_info_path) %>">
            <%= link_to '¿Quién soy?', pages_info_path %>
          </li>
          <li class="<%= 'active' if current_page?(new_idea_path) %>">
            <%= link_to 'Nueva Idea', new_idea_path %>
          </li>
        </ul>
        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Hola <strong><%= current_user.email %> !</strong>.
          <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Registrarse", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Iniciar sesión", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>

  <footer>
    <div class="container">
      Rails Girls 2015
    </div>
  </footer>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>